#!/usr/bin/env node
/**
 * Venue layer import (PLAN.md §6): pull court/park POIs for the launch metro
 * from OpenStreetMap via Overpass, dedupe against nearby duplicates, and emit
 * an idempotent SQL file for the venues table.
 *
 * Usage:
 *   node scripts/import-venues.mjs                # Austin (default)
 *   node scripts/import-venues.mjs --bbox 30.09,-97.95,30.52,-97.55
 *
 * Output: supabase/venues_import.sql — review, then apply with
 *   pnpm dlx supabase db execute --file supabase/venues_import.sql
 * (or paste into the dashboard SQL editor).
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

// Austin metro bbox (south,west,north,east)
const DEFAULT_BBOX = "30.09,-97.95,30.52,-97.55";

const bboxArg = process.argv.indexOf("--bbox");
const bbox = bboxArg > -1 ? process.argv[bboxArg + 1] : DEFAULT_BBOX;

// leisure=pitch with the launch sports (§6); OSM sport tags are lowercase.
// running tracks come from leisure=track + sport=running|athletics.
const query = `
[out:json][timeout:90];
(
  nwr["leisure"="pitch"]["sport"~"^(pickleball|tennis|basketball)$"](${bbox});
  nwr["leisure"="pitch"]["sport"~"pickleball"](${bbox});
  nwr["leisure"="track"]["sport"~"^(running|athletics)$"](${bbox});
);
out center tags;
`;

const OVERPASS_URLS = [
  "https://overpass-api.de/api/interpreter",
  "https://overpass.kumi.systems/api/interpreter",
];

function sportsFromTags(tags) {
  const raw = (tags.sport ?? "").toLowerCase();
  const sports = new Set();
  for (const s of raw.split(";").map((x) => x.trim())) {
    if (s === "pickleball" || s === "tennis" || s === "basketball") sports.add(s);
    if (s === "running" || s === "athletics") sports.add("running");
  }
  return [...sports];
}

function escapeSql(s) {
  return s.replace(/'/g, "''");
}

let data = null;
for (const url of OVERPASS_URLS) {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Accept: "application/json",
      "User-Agent": "pickup-sports-venue-import/0.1 (one-time seed script)",
    },
    body: `data=${encodeURIComponent(query)}`,
  });
  if (res.ok) {
    data = await res.json();
    break;
  }
  console.error(`Overpass ${url} failed: ${res.status} ${res.statusText}`);
}
if (!data) process.exit(1);

const seen = new Set();
const rows = [];
for (const el of data.elements ?? []) {
  const tags = el.tags ?? {};
  const sports = sportsFromTags(tags);
  if (sports.length === 0) continue;
  const lat = el.lat ?? el.center?.lat;
  const lon = el.lon ?? el.center?.lon;
  if (lat == null || lon == null) continue;

  const name =
    tags.name ??
    `${sports[0][0].toUpperCase()}${sports[0].slice(1)} court${tags["addr:street"] ? ` — ${tags["addr:street"]}` : ""}`;

  // dedupe unnamed courts that sit within ~50m of one another (court clusters)
  const key = `${name}|${lat.toFixed(3)},${lon.toFixed(3)}`;
  if (seen.has(key)) continue;
  seen.add(key);

  const address = [tags["addr:housenumber"], tags["addr:street"], tags["addr:city"]]
    .filter(Boolean)
    .join(" ");
  const courtCount = /^\d+$/.test(tags.capacity ?? "") ? Number(tags.capacity) : null;

  rows.push({ name: name.slice(0, 120), sports, lat, lon, address, courtCount, osmId: `${el.type}/${el.id}` });
}

if (rows.length === 0) {
  console.error("No venues found — check the bbox or Overpass availability.");
  process.exit(1);
}

const values = rows
  .map(
    (r) =>
      `  ('${escapeSql(r.name)}', '{${r.sports.join(",")}}'::sport[], st_point(${r.lon}, ${r.lat})::geography, ${
        r.address ? `'${escapeSql(r.address)}'` : "null::text"
      }, ${r.courtCount ?? "null::int"}, 'osm'::venue_source, false)`
  )
  .join(",\n");

const sql = `-- Generated by scripts/import-venues.mjs (${new Date().toISOString()})
-- Source: OpenStreetMap via Overpass (bbox ${bbox}) — ODbL attribution applies.
-- ${rows.length} venues. Idempotent: skips names already present.

insert into venues (name, sports, location, address, court_count, source, verified)
select v.* from (values
${values}
) as v(name, sports, location, address, court_count, source, verified)
where not exists (
  select 1 from venues x
  where x.name = v.name
    and st_dwithin(x.location, v.location, 100)
);
`;

const outPath = resolve(import.meta.dirname, "../supabase/venues_import.sql");
writeFileSync(outPath, sql);
const bySport = {};
for (const r of rows) for (const s of r.sports) bySport[s] = (bySport[s] ?? 0) + 1;
console.log(`Wrote ${rows.length} venues to ${outPath}`);
console.log(`By sport: ${JSON.stringify(bySport)}`);
